rooms: [R2, R3]
# rooms: [R2, R3, R4, R5, R6, R7, R8, R9, R10, R11]
start_node_id: R1
distribution_node: R1
maintenance_node: R1
max_rooms: 2
# max_rooms: 10
max_traversal_cost: 1
graph_generator_type: simple_hallway
graph_filename: None
distance_scaling: 1