variance_bias: 0.1
num_paths: 5
num_worlds: 5
max_iterations: 1000
planning_horizon: 10
min_expansions: 10
discovery_factor: 1.41421356237
uncertainty_penalty: .5
observation_reward: 0.0
deliver_threshold: .75