# budget: 1440
budget: 60
time_interval: 1
start_time: 0
node_closeness: random
availabilities: brayford
sampling_method: gauss
temporal_consistency: 1
availability_length: 0
availability_chance: 0
maintenance_reward: 0.001
deliver_reward: 1.0
max_noise_amplitude: 0.0
schedule_generation_method: temporal_consistency
data_path: /datasets/brayford/
