# budget: 60
budget: 120
time_interval: 1
start_time: 0
node_closeness: sequential
availabilities: windows
sampling_method: gauss
temporal_consistency: 1
# availability_length: 20
availability_length: 30
availability_chance: 0.6
maintenance_reward: 0.001
deliver_reward: 1.0
max_noise_amplitude: 0.0
schedule_generation_method: temporal_consistency