spacing: 1
# noise_scaling: 0.02
use_gp: 0
separate_mus: 0
shortest_period: 30
#60
# shortest_period: 43200 #60*60*12
longest_period: 1440
#60*24
# longest_period: 2419200 #60*60*24*28
num_clusters: 9
num_iterations: 100
version: hard
fuzzyfier: 1
lambda_param: 5
ensemble_method: BMA
